#!/bin/sh

./CLEANUP

mkdir google
cd google

mkdir api
curl https://raw.githubusercontent.com/googleapis/googleapis/master/google/api/annotations.proto >> api/annotations.proto
curl https://raw.githubusercontent.com/googleapis/googleapis/master/google/api/client.proto >> api/client.proto
curl https://raw.githubusercontent.com/googleapis/googleapis/master/google/api/field_behavior.proto >> api/field_behavior.proto
curl https://raw.githubusercontent.com/googleapis/googleapis/master/google/api/http.proto >> api/http.proto

mkdir protobuf
curl https://raw.githubusercontent.com/protocolbuffers/protobuf/master/src/google/protobuf/descriptor.proto >> protobuf/descriptor.proto

mkdir -p cloud/language/v1
curl https://raw.githubusercontent.com/googleapis/googleapis/master/google/cloud/language/v1/language_service.proto >> cloud/language/v1/language_service.proto

cd ..

echo "Checking path of the directory"
pwd


echo "Installing Cocoapod dependencies"
pod install

echo "Opening the project workspace in Xcode"
open NaturalLanguage.xcworkspace

echo "Now press the run button!"


